storage assignment submission
Naveen-Goud/zemoso-training pull request #6
Opened 2023-03-08 10:56 UTC by Naveen-Goud

stroage assignment review submission.

2023-03-09 06:41 UTC, msaisrinivas requested changes

2023-03-09 06:41 UTC, msaisrinivas commented on stroageassignment.html
> +        <script>
if values are already present in the storage, then get the values from the storage.

2023-03-09 06:41 UTC, msaisrinivas commented on stroageassignment.html
> +               if(sessionStorage.clickCounter){
Rather than checking over here, you can create and initialize the value with 0. if it's not present in the storage.

2023-03-13 07:00 UTC, msaisrinivas approved these changes

2023-03-13 07:03 UTC, Naveen-Goud commented
stroage assignment completed

2023-03-13 07:03 UTC, merged